# Generated by Django 5.1 on 2024-08-22 07:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('entry_num', models.IntegerField(blank=True, null=True)),
                ('heading', models.CharField(blank=True, max_length=800, null=True)),
                ('key_point1', models.CharField(blank=True, max_length=200, null=True)),
                ('key_point2', models.CharField(blank=True, max_length=200, null=True)),
                ('key_point3', models.CharField(blank=True, max_length=200, null=True)),
                ('key_point4', models.CharField(blank=True, max_length=200, null=True)),
                ('minute_read', models.CharField(blank=True, max_length=5, null=True)),
                ('primary_note', models.CharField(blank=True, max_length=1000, null=True)),
                ('sub_heading1', models.CharField(blank=True, max_length=800, null=True)),
                ('picture1', models.CharField(blank=True, max_length=500, null=True)),
                ('sub_text1', models.TextField(blank=True, max_length=1200, null=True)),
                ('sub_heading2', models.CharField(blank=True, max_length=800, null=True)),
                ('picture2', models.CharField(blank=True, max_length=500, null=True)),
                ('sub_text2', models.TextField(blank=True, max_length=1200, null=True)),
                ('sub_heading3', models.CharField(blank=True, max_length=800, null=True)),
                ('picture3', models.CharField(blank=True, max_length=500, null=True)),
                ('sub_text3', models.TextField(blank=True, max_length=1200, null=True)),
                ('sub_heading4', models.CharField(blank=True, max_length=800, null=True)),
                ('picture4', models.CharField(blank=True, max_length=500, null=True)),
                ('sub_text4', models.TextField(blank=True, max_length=1200, null=True)),
                ('sub_heading5', models.CharField(blank=True, max_length=800, null=True)),
                ('picture5', models.CharField(blank=True, max_length=500, null=True)),
                ('sub_text5', models.TextField(blank=True, max_length=1200, null=True)),
                ('conclusion', models.TextField(blank=True, max_length=1200, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
    ]
