# Generated by Django 5.1 on 2024-08-22 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Articles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='key_point1',
        ),
        migrations.RemoveField(
            model_name='articles',
            name='key_point2',
        ),
        migrations.RemoveField(
            model_name='articles',
            name='key_point3',
        ),
        migrations.RemoveField(
            model_name='articles',
            name='key_point4',
        ),
        migrations.AddField(
            model_name='articles',
            name='key_point',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
