# Generated by Django 5.1 on 2024-08-18 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Work', '0002_experiences_duties'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experiences',
            name='duties',
        ),
        migrations.AddField(
            model_name='experiences',
            name='duty1',
            field=models.CharField(blank=True, max_length=800, null=True),
        ),
        migrations.AddField(
            model_name='experiences',
            name='duty2',
            field=models.CharField(blank=True, max_length=800, null=True),
        ),
        migrations.AddField(
            model_name='experiences',
            name='duty3',
            field=models.CharField(blank=True, max_length=800, null=True),
        ),
        migrations.AddField(
            model_name='experiences',
            name='duty4',
            field=models.CharField(blank=True, max_length=800, null=True),
        ),
    ]
