# Generated by Django 5.1 on 2024-08-18 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Work', '0003_remove_experiences_duties_experiences_duty1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='experiences',
            name='entry_num',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
