# Generated by Django 5.1 on 2024-08-18 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Work', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='experiences',
            name='duties',
            field=models.CharField(blank=True, max_length=800, null=True),
        ),
    ]
