# Generated by Django 5.1 on 2024-08-17 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_image', models.ImageField(blank=True, default=None, null=True, upload_to='')),
                ('certification_name', models.CharField(max_length=700)),
                ('certification_description', models.TextField(max_length=1000)),
                ('certificate_image', models.ImageField(blank=True, default=None, null=True, upload_to='')),
            ],
        ),
    ]
