# Generated by Django 5.1 on 2024-08-18 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('About', '0004_certifications_created_alter_certifications_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certifications',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
