# Generated by Django 5.1 on 2024-08-24 06:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certifications',
            fields=[
                ('cover_image_url', models.CharField(blank=True, max_length=500, null=True)),
                ('certification_name', models.CharField(max_length=700)),
                ('certification_description', models.TextField(max_length=1000)),
                ('certificate_image_url', models.CharField(blank=True, max_length=500, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
    ]
