# Generated by Django 5.1 on 2024-08-22 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Articles', '0002_remove_articles_key_point1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
